name : CI Pipeline

on :
  push : 
    branches : [ master ]


jobs: 
  build: 
    runs-on: ubuntu-latest
    steps : 
      - name : checkout code 
        uses : actions/checkout@v5
      
      - name : set up node jobs
        uses : actions/setup-node@v3
        with : 
          node-version: 16
        
      - name : Install dependencies
        run : npm install 
      
      - name : run tests 
        run : npm test 

